[package]
name = "generic-json"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc-traits = { path = "../../traits/cc-traits", features = ["nightly", "serde_json"] }
# json = "*"
serde_json = "*"